version: "3"
services:
  nginx:
    image: nginx
  alpine:
    image: alpine
    entrypoint: "wget http://nginx"
#    After ping I have to input the service name
    depends_on:
      - nginx
    working_dir: /searchforme
#    depends_on --> this makes sure that this service will not be started before another one. This only orders the services
# in case first service has latency, second service will start faster
